name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: okc0202/nahc
          stage: main
          yaml: >
            name: vett-frontend

            app: web

            options:
              nodeversion: "22"
              spa: true
              buildenv:
                - name: VITE_KAKAO_REST_API_KEY
                  value: ${{ secrets.VITE_KAKAO_REST_API_KEY }}
                - name: VITE_KAKAO_SECRET
                  value: ${{ secrets.VITE_KAKAO_SECRET }}
                - name: VITE_NAVER_REST_API_KEY
                  value: ${{ secrets.VITE_NAVER_REST_API_KEY }}
                - name: VITE_NAVER_SECRET
                  value: ${{ secrets.VITE_NAVER_SECRET }}
                - name: VITE_GOOGLE_CLIENT_ID
                  value: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
                - name: VITE_GOOGLE_USERINFO_REQUEST_URL
                  value: ${{ secrets.VITE_GOOGLE_USERINFO_REQUEST_URL }}
              rewrites:
                - path: /api/naver/token
                  target: ${{ secrets.VITE_NAVER_TOKEN_TARGET }}
                - path: /api/naver/user
                  target: ${{ secrets.VITE_NAVER_USER_TARGET }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react-vite